kevin-lee/jdk-sym-link

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/Shell.scala, core/src/main/scala/jdksymlink/core/Utils.scala
=> Clean up <* 🎉 2020

build.sbt
=> Renamed: CLI executable name

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, project/build.properties
Upgraded - sbt `1.3.6` => `1.3.7`
=> Upgraded - sbt 1.3.6 => 1.3.7

build.sbt, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/effect/Effect.scala, core/src/main/scala/jdksymlink/effect/package.scala
Close #33 - Make JdkSymLink referentially transparent
=> Close #33 - Make JdkSymLink referentially transparent

build.sbt
=> Upgraded: pirate

core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Task #33 - use the actual constructor method for preferential transparency
=> Task #33 - use the actual constructor method for preferential transparency

build.sbt
Upgraded - cats-effect 2.0.0 => 2.1.1
=> Upgraded - cats-effect 2.0.0 => 2.1.1

core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Cleanup - Removed: Unnecessary implicit fields
=> Cleanup - Removed: Unnecessary implicit fields

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/effect/Effect.scala
Added: `trait` to have an effect constructor method in a simple way.
=> Added: trait to have an effect constructor method in a simple way

cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/effect/Effects.scala, core/src/main/scala/jdksymlink/effect/package.scala
=> Clean up and rename

build.sbt
Updated: `build.sbt` to have common sub-project config
=> Updated: build.sbt to have common sub-project config

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/effect/Effects.scala
Changed: Parametric Polymorphism => Ad hoc Polymorphism in Effect utils
=> Changed: Parametric Polymorphism => Ad hoc Polymorphism in Effect utils

build.sbt
Upgraded: Cats and Cats Effect
* Cats 2.1.0 => 2.1.1
* Cats Effect 2.1.1 => 2.1.3
=> Upgraded: Cats and Cats Effect

.github/workflows/build.yml, .github/workflows/sbt-build-all.sh, build.sbt, core/src/main/scala/jdksymlink/core/JdkSymLink.scala
* Hedgehog: => 0.6.1
* Effectie: 0.4.0 => 1.8.1
* Cats: 2.1.1 => 2.3.1
* Cats Effect: 2.1.3 => 2.3.1
* Pirate: => b3a0a3eff3a527dff542133aaf0fd935aa2940fc
* just-sysprocess: 0.3.0
=> Upgraded: libraries

.github/workflows/build.yml, build.sbt, project/SbtProjectInfo.scala
=> Updated: Project config

.scalafmt.conf
=> Added: scalafmt config

project/build.properties
=> Upgraded: sbt 1.3.8 => 1.4.6

.scalafmt.conf
=> Updated: .scalafmt.conf

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, core/src/main/scala/jdksymlink/core/data.scala
Upgraded: Scala 2.13.3 => 2.13.4 and 2.13.x => 2.13.4 in GitHub Actions config
=> Upgraded: Scala 2.13.3 => 2.13.4 and 2.13.x => 2.13.4 in GitHub Actions config

build.sbt, project/plugins.sbt
Upgraded: libraries and plugins
=> Upgraded: libraries and plugins

cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala
=> Close #23 - Add proper errors

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, project/plugins.sbt
Upgraded: sbt-devoops `1.0.3` => `2.0.0`
=> Upgraded: sbt-devoops 1.0.3 => 2.0.0

.github/workflows/release.yml
* Import `jdk-ln-s` from my gist (#12)
* Add proper CLI (#13)
* Make cli use core (#20)
* Use tagless-final (#25)
* Remove `JdkSymLinkBridge` (#28)
* Make `JdkSymLink` referentially transparent (#33)
* Add proper errors (#23)
* Add installation script (#61)
=> jdk-sym-link v0.1.0

.scripts/install.sh
Close #61 - Add installation script
=> Close #61 - Add installation script

cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala
Close #66 - Remove unnecessary java version param name
=> Close #66 - Remove unnecessary java version param name

core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Shell.scala
Close #68 - Better way to handle console color
=> Close #68 - Better way to handle console color

core/src/main/scala/jdksymlink/core/Shell.scala
Close #71 - Error message contains irrelevant words
=> Close #71 - Error message contains irrelevant words

.scripts/install.sh, README.md
=> Added: How to install

build.sbt
=> Clean up - build.sbt

build.sbt
=> Upgrade lib

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, cli/src/main/scala/jdksymlink/cli/JdkSymLinkArgs.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/Shell.scala, core/src/main/scala/jdksymlink/core/data.scala, project/plugins.sbt
Close #75 - Use Scala `3.0.0-RC1`
=> Close #75 - Use Scala 3.0.0-RC1

.github/workflows/manual-graalvm-gh-release.yml, build.sbt
Added: GitHub Actions config for manual GitHub Release for GraalVM Native Image
=> Added: GitHub Actions config for manual GitHub Release for GraalVM Native Image

.github/workflows/manual-graalvm-gh-release.yml
Fixed: Manual GH Release config
=> Fixed: Manual GH Release config

.github/workflows/m-upload-graalvm-to-gh-release.yml
Fixed: Remove GH Release from manual upload to GH release
=> Fixed: Remove GH Release from manual upload to GH release

.scripts/install.sh
Close #84 - Update installation script to install the GraalVM Native Image version of `jdk-sym-link`
=> Close #84 - Update installation script to install the GraalVM Native Image version of jdk-sym-link

.scalafmt.conf, build.sbt, cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, cli/src/main/scala/jdksymlink/cli/JdkSymLinkArgs.scala, core/src/main/scala/effectie/instances/package.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Shell.scala, core/src/main/scala/jdksymlink/core/data.scala, project/plugins.sbt
Close #92 - Use more Scala 3 only features
=> Close #92 - Use more Scala 3 only features

cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/Utils.scala
=> Formatting

cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Shell.scala, core/src/main/scala/jdksymlink/core/data.scala
Close #98 - Use `enum`'s data constructor and more `extension` methods
=> Close #98 - Use enum's data constructor and more extension methods

.scripts/install.sh
Updated: The installation script for `v0.3.0`
=> Updated: The installation script for v0.3.0

build.sbt
=> Updated: config

cli/src/main/scala/jdksymlink/cli/JdkSymLinkArgs.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Shell.scala, core/src/main/scala/jdksymlink/core/data.scala
Use CanEqual instead of Eql and add CanEqual typeclass instance for Either and Tuple.
=> Use CanEqual instead of Eql and add CanEqual typeclass instance for Either and Tuple

build.sbt
Upgraded: Scala `3.0.0-RC3` => `3.0.0`
=> Upgraded: Scala 3.0.0-RC3 => 3.0.0

.scripts/install.sh
Updated: The installation script
=> Updated: The installation script

cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Utils.scala, core/src/main/scala/jdksymlink/core/data.scala, core/src/main/scala/jdksymlink/instances/all.scala
Close #110 - Move CanEqual typeclass instances to instances package
=> Close #110 - Move CanEqual typeclass instances to instances package

build.sbt, project/plugins.sbt
Upgraded: `sbt-devoops` `2.3.0` => `2.6.0`
=> Upgraded: sbt-devoops 2.3.0 => 2.6.0

cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/Utils.scala, core/src/main/scala/jdksymlink/core/data.scala
Close #119 - Support JDK installed by Coursier
=> Close #119 - Support JDK installed by Coursier

.scripts/install.sh
Updated: install.sh with the new version
=> Updated: install.sh with the new version

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/data.scala
Fix #127 - Fixed: Error when Coursier jvm directory doesn't exist
=> Fix #127 - Fixed: Error when Coursier jvm directory doesn't exist

core/src/main/scala/jdksymlink/core/data.scala
Fix #126 - Fixed: User home directory is not retrieved in runtime
=> Fix #126 - Fixed: User home directory is not retrieved in runtime

core/src/main/scala/jdksymlink/core/JdkSymLink.scala
=> Clean up - unnecessary log

core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/data.scala
Close #133 - Error when there's no file in the JDK directories
=> Close #133 - Error when there's no file in the JDK directories

.scripts/install.sh
Updated: install.sh with the new version - `0.5.2`
=> Updated: install.sh with the new version - 0.5.2

.scripts/install.sh
Updated: The installation scripts with better `PATH` setup
=> Updated: The installation scripts with better PATH setup

core/src/main/scala/jdksymlink/core/Utils.scala, core/src/main/scala/jdksymlink/core/data.scala
Close #147 - Support `temurin` (`Adoptium`)
=> Close #147 - Support temurin (Adoptium)

.scripts/install.sh
Updated: The `install.sh` with the new version (`0.7.0`)
=> Updated: The install.sh with the new version (0.7.0)

.github/workflows/release.yml
Fix GitHub Actions config for release
=> Fix GitHub Actions config for release

.scripts/install-jvm.sh, README.md
=> Fix install-jvm.sh

.scalafmt.conf, cli/src/main/scala/jdksymlink/cli/JdkSymLinkArgs.scala, cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/Utils.scala, core/src/main/scala/jdksymlink/core/data.scala
Update: `.scalafmt.conf` - new formatting rules and reformat the code
=> Update: .scalafmt.conf - new formatting rules and reformat

build.sbt, cli/src/main/scala/jdksymlink/cli/JdkSymLinkAppError.scala, cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/cs/CoursierCmd.scala
Close #166 - List JDK paths from Coursier (`cs java --installed`)
=> Close #166 - List JDK paths from Coursier (`cs java --installed`)

cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala, core/src/main/scala/jdksymlink/core/data.scala, core/src/main/scala/jdksymlink/cs/CoursierCmd.scala, project/plugins.sbt
Close #167 - Symlink to JDKs from Coursier (`cs java --installed`)
=> Close #167 - Symlink to JDKs from Coursier (cs java --installed)

.scripts/install-jvm.sh, .scripts/install.sh
Update: `install.sh` and `install-jvm.sh` with `v0.9.0`
=> Update: install.sh and install-jvm.sh with v0.9.0

.github/pr-labeler.yml
=> Close #175 - Add PR labeler

.github/workflows/pr-labeler.yml
Close #175 - Add the missing `.github/workflows/pr-labeler.yml`
=> Close #175 - Add the missing .github/workflows/pr-labeler.yml

core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, core/src/main/scala/jdksymlink/core/data.scala, core/src/main/scala/jdksymlink/cs/CoursierCmd.scala
Fix #174 - Error when JDK version is neither `SemVer` nor decimal version
=> Fix #174 - Error when JDK version is neither `SemVer` nor decimal version

.github/workflows/build.yml, .github/workflows/m-upload-graalvm-to-gh-release.yml, build.sbt
Updated: Graal native image version to 22.1.0 and use Java 17
=> Updated: Graal native image version to 22.1.0 and use Java 17

.scalafix.conf
=> Add: .scalafix.conf

build.sbt
Update: `build.sbt` - `nativeImageVersion` `22.1.0` => `22.2.0`
=> Update: build.sbt - nativeImageVersion 22.1.0 => 22.2.0

build.sbt, cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala, cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala, cli/src/main/scala/jdksymlink/cli/MainIo.scala, core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Close #211 - Bump effectie to `2.0.0-beta2` and fix broken code due to breaking changes in `2.0.0-beta2`
=> Close #211 - Bump effectie to 2.0.0-beta2 and fix broken code due to breaking changes in 2.0.0-beta2

project/plugins.sbt
=> Remove unused config

.scalafmt.conf, build.sbt
=> Reformat `build.sbt`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/task-template.md, .scripts/install-jvm.sh, .scripts/install.sh, README.md, build.sbt, changelogs/0.1.0.md, changelogs/0.2.0.md, changelogs/0.2.1.md, changelogs/0.3.0.md, changelogs/0.4.0.md, changelogs/0.5.0.md, changelogs/0.5.1.md, changelogs/0.5.2.md, changelogs/0.6.0.md, changelogs/0.7.0.md, changelogs/0.8.0.md, changelogs/0.9.0.md, changelogs/0.9.1.md
Update: config - `Kevin-Lee` => `kevin-lee`
=> Update: config - `Kevin-Lee` => `kevin-lee`

modules/jdk-sym-link-cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/Utils.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/data.scala
=> Close #332 - Support SdkMan!

build.sbt, project/SbtProjectInfo.scala, version.sbt
Add: `version.sbt` - with the project version so no more `SbtProjectInfo.scala` to set the version
=> Add: `version.sbt` - with the project version so no more `SbtProjectInfo.scala` to set the version

modules/jdk-sym-link-cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Close #333 - Drop Coursier support
=> Close #333 - Drop Coursier support

build.sbt
Close #351 - Add `refined4s` as a dependency library
=> Close #351 - Add `refined4s` as a dependency library

build.sbt, modules/jdk-sym-link-cli/src/main/scala/jdksymlink/cli/JdkSymLinkAppError.scala, modules/jdk-sym-link-cli/src/main/scala/jdksymlink/cli/MainIo.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/JdkSymLink.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/data.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/cs/CoursierCmd.scala
Close #353 - Replace custom newtypes (`opaque type`s) with `refined4s`
=> Close #353 - Replace custom newtypes (`opaque type`s) with `refined4s`

.scripts/install-jvm.sh, .scripts/install.sh
=> Update installation scripts

build.sbt
Bump pirate to `faff703b67fd10199098e806a3f6858982823461`
=> Bump pirate to `faff703b67fd10199098e806a3f6858982823461`

build.sbt
=> Bump `refined4s` to `0.8.0`

build.sbt, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/data.scala
Close #362 - Use `refined4s-extras-render`
=> Close #362 - Use `refined4s-extras-render`

build.sbt
Bump `refined4s` and `pirate`
* refined4s to `0.11.0`
* pirate to `574d85a36919280dc802009b581df9019811c27e`
=> Bump refined4s and pirate

build.sbt
=> Bump effectie to 2.0.0-beta14

build.sbt, modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Close #379 - Bump Scala to 3.4.0
=> Close #379 - Bump Scala to 3.4.0

build.sbt
Downgrade Scala from 3.4.0 to 3.3.3 as 3.3 is LTS
=> Downgrade Scala from 3.4.0 to 3.3.3 as 3.3 is LTS

build.sbt
=> Add kittens

modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/data.scala, modules/jdk-sym-link-core/src/main/scala/jdksymlink/cs/CoursierCmd.scala
Add `Eq` and `Show` type-classes
- Also use kittens for `Eq` and `Show`
=> Add `Eq` and `Show` type-classes

.github/workflows/build.yml, .github/workflows/m-upload-graalvm-to-gh-release.yml, .github/workflows/release.yml
Update GitHub Actions config: Replace `olafurpg/setup-scala` with `actions/setup-java`
=> Update GitHub Actions config: Replace `olafurpg/setup-scala` with `actions/setup-java`

.github/workflows/build.yml, .github/workflows/release.yml
Close #417 - Fix `release.yml` - fix the app binary name
=> Close #417 - Fix `release.yml` - fix the app binary name

version.sbt
Update `version.sbt` with `1.2.0`
=> Update `version.sbt` with `1.2.0`

.github/workflows/build.yml, .github/workflows/m-upload-graalvm-to-gh-release.yml, .github/workflows/release.yml
Update: GitHub Actions
- Remove macOS 12 and add macOS 15
=> Update: GitHub Actions
