kevin-lee/jdk-sym-link

- cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala
- cli/src/main/scala/jdksymlink/cli/MainIo.scala
* Renamed: `MainIO` => `MainIo`
* Removed: Unnecessary type alias, `SIO`
> Renamed and removed

- core/src/main/scala/jdksymlink/core/JdkSymLink.scala
Minor change in JdkSymLinkF: `def` => `val`
> Minor change in JdkSymLinkF: def => val

- changelogs/0.1.0.md
* Import `jdk-ln-s` from my gist (#12)
* Add proper CLI (#13)
* Make cli use core (#20)
* Use tagless-final (#25)
* Remove `JdkSymLinkBridge` (#28)
* Make `JdkSymLink` referentially transparent (#33)
* Add proper errors (#23)
* Add installation script (#61)
> jdk-sym-link v0.1.0

- build.sbt
Fixed: `DevOopsGitReleasePlugin` => `DevOopsGitHubReleasePlugin`
> Fixed: DevOopsGitReleasePlugin => DevOopsGitHubReleasePlugin

- .scripts/install.sh
- changelogs/0.2.0.md
- project/SbtProjectInfo.scala
* Remove unnecessary java version param name (#66)
* Better way to handle console color (#68)
> jdk-sym-link v0.2.0

- changelogs/0.2.1.md
- project/SbtProjectInfo.scala
* Error message contains irrelevant words (i.e. `Reset`) (#71)
e.g.)
Before
```
ErrorCodeReset: 1
ErrorReset: sudo: 3 incorrect password attempts
when running [sudo, rm, jdk8]
```
Now
```
ErrorCode: 1
Error: sudo: 3 incorrect password attempts
when running [sudo, rm, jdk8]
```
> jdk-sym-link v0.2.1

- changelogs/0.3.0.md
- project/SbtProjectInfo.scala
* Use Scala `3.0.0-RC1` (#75)
* Build with GraalVM (#81)
* Update installation script to install the GraalVM Native Image version of `jdk-sym-link` (#84)
* Upgrade Scala to `3.0.0-RC3` (#90)
* Use more Scala 3 only features (#92)
* Make error message more readable (#96)
* Use `enum`'s data constructor and more `extension` methods (#98)
> jdk-sym-link v0.3.0

- core/src/main/scala/jdksymlink/core/data.scala
Added: Typeclass `CanEqual` instance for `CanEqual[Option[T], Option[U]]`
> Added: Typeclass CanEqual instance for CanEqual[Option[T], Option[U]]

- changelogs/0.4.0.md
- project/SbtProjectInfo.scala
* Upgrade Scala to 3.0.0 (#106)
> jdk-sym-link v0.4.0

- changelogs/0.5.0.md
- project/SbtProjectInfo.scala
* Move `CanEqual` typeclass instances to instances package (#110)
* Replace `CanEqual` instances with `can-equal` (#113)
* Support JDK installed by Coursier (#119)
> jdk-sym-link v0.5.0

- core/src/main/scala/jdksymlink/core/data.scala
Fix #126 - Fixed: User home directory is not retrieved in runtime
> Fix #126 - Fixed: User home directory is not retrieved in runtime

- .scripts/install.sh
- changelogs/0.5.1.md
- project/SbtProjectInfo.scala
* User home directory is not retrieved in runtime (#126)
* Error when Coursier jvm directory doesn't exist (#127)
> jdk-sym-link v0.5.1

- changelogs/0.5.2.md
- project/SbtProjectInfo.scala
* Error when there's no file in the JDK directories (#133)
> jdk-sym-link v0.5.2

- changelogs/0.7.0.md
- project/SbtProjectInfo.scala
* Upgrade Scala to `3.1.0` (#145)
* Support `temurin` (`Adoptium`) (#147)
> jdk-sym-link v0.7.0

- .scripts/install-jvm.sh
- changelogs/0.8.0.md
- project/SbtProjectInfo.scala
* Add build for package for JVM (for M1 Mac) (#152)
> jdk-sym-link v0.8.0

- build.sbt
- cli/src/main/scala/jdksymlink/cli/JdkSymLinkApp.scala
- cli/src/main/scala/jdksymlink/cli/JdkSymLinkAppError.scala
- cli/src/main/scala/jdksymlink/cli/JdkSymLinkArgs.scala
- cli/src/main/scala/jdksymlink/cli/JdkSymLinkRun.scala
- cli/src/main/scala/jdksymlink/cli/MainIo.scala
- core/src/main/scala/jdksymlink/core/JdkSymLink.scala
- core/src/main/scala/jdksymlink/core/JdkSymLinkError.scala
Close #159 - Upgrade Scala and libraries (`cats-effect`, `effectie`, etc.)
- `effectie` `1.15.0` => `2.0.0-beta1`
- Scala `3.1.0` => `3.1.2`
- Remove `can-equal`
- `refined` `0.9.25` => `0.9.27`
- `cats` `2.6.1` => `2.7.0`
- `cats-effect` `2.5.4` => `3.3.12`
- `extras` `0.1.0` => `0.14.0`
> Close #159 - Upgrade Scala and libraries (`cats-effect`, `effectie`, etc.)

- build.sbt
- changelogs/0.9.0.md
- project/SbtProjectInfo.scala
* Upgrade Scala and libraries (`cats-effect`, `effectie`, etc.) (#159)
* `effectie` `1.15.0` => `2.0.0-beta1` - `effectie-cats-effect` => `effectie-cats-effect3`
* Remove `effectie-scalaz-effect`
* Scala `3.1.0` => `3.1.2`
* Remove `can-equal`
* `refined` `0.9.25` => `0.9.29`
* `cats` `2.6.1` => `2.7.0`
* `cats-effect` `2.5.4` => `3.3.12`
* `extras` `0.1.0` => `0.15.0`
* Add `just-semver` `0.5.0`
* Add `extras-scala-io` `0.15.0`
* List JDK paths from Coursier (`cs java --installed`) (#166)
* Symlink to JDKs from Coursier (`cs java --installed`) (#167)
> jdk-sym-link v0.9.0

- .scripts/install-jvm.sh
- .scripts/install.sh
- changelogs/0.9.1.md
- project/SbtProjectInfo.scala
* Error when JDK version is neither `SemVer` nor decimal version (#174)
* Add PR labeler (#175)
* Add `dependabot` for GitHub Actions (#177)
> jdk-sym-link v0.9.1

- changelogs/0.10.0.md
* Support [SdkMan!](https://sdkman.io) (#332)
* Bump effectie to `2.0.0-beta2` (#211)
* Bump to `2.0.0-beta13`
> jdk-sym-link v0.10.0

- modules/jdk-sym-link-core/src/main/scala/jdksymlink/core/data.scala
Fix #336 - Native image is using the HOME of build environment instead of the running environment's
> Fix #336 - Native image is using the HOME of build environment instead of the running environment's

- .scripts/install-jvm.sh
- .scripts/install.sh
- changelogs/0.10.1.md
- version.sbt
* Fix: Native image is using the HOME of build environment instead of the running environment's (#336)
> jdk-sym-link v0.10.1

- .scripts/install-jvm.sh
- .scripts/install.sh
- changelogs/1.0.0.md
- version.sbt
* Drop Coursier support (#333)
> jdk-sym-link v1.0.0

- changelogs/1.1.0.md
- version.sbt
* Add `refined4s` as a dependency library (#351)
* Replace custom newtypes (`opaque type`s) with `refined4s` (#353)
> jdk-sym-link v1.1.0

- .github/workflows/build.yml
- .github/workflows/m-upload-graalvm-to-gh-release.yml
Close #379 - Bump Scala to 3.4.0 - update GitHub Actions
> Close #379 - Bump Scala to 3.4.0 - update GitHub Actions

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
Close #417 - GitHub Actions: Add builds with `macos-13` and `macos-14` (Apple Silicon)
> Close #417 - GitHub Actions: Add builds with `macos-13` and `macos-14` (Apple Silicon)

- changelogs/1.2.0.md
* GitHub Actions: Add builds with `macos-13 and` `macos-14` (Apple Silicon) (#417)
* Bump Scala to `3.3.4` (#379)
* Use `refined4s-extras-render` (#362)
> jdk-sym-link v1.2.0

- .scripts/install-jvm.sh
- .scripts/install.sh
- changelogs/1.3.0.md
- version.sbt
* Drop supporting macOS 12 and add a new native version works built for macOS 15
So it supports the following macOS versions:
* macOS 13 (Intel)
* macOS 14 (Apple Silicon)
* macOS 15 (Apple Silicon)
> jdk-sym-link v1.3.0

- .gitignore
Update `.gitignore` to exclude .bloop and Metals configuration files
> Update `.gitignore` to exclude .bloop and Metals configuration files
